# Generated by Django 6.0.4 on 2026-04-13 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('rows_total', models.IntegerField()),
                ('rows_inserted', models.IntegerField()),
                ('rows_deduped', models.IntegerField()),
                ('rows_failed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truckstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('issue_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('raw_payload', models.JSONField()),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='stations.importjob')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stations.rack')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='truckstop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='stations.truckstop'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('truckstop', 'rack_id'), name='unique_rack_per_truckstop'),
        ),
    ]
